#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x easy_cache`
puts `gem build easy_cache.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
